version: '3.8'

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - GRAFANA_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    networks:
      - poti-net
    restart: always

networks:
  poti-net:
    external: true
