server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    # File Upload (Multipart)
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  forward-headers-strategy: framework

spring:
  application:
    name: poti-server

  # Database (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ???(Asia/Seoul)? ???(utf8mb4) ?? ??
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/poti?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # ??? update, ?? ? validate? ?? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: false # P6Spy? ??? false? ?? (?? ?? ??)
        default_batch_fetch_size: 100 # N+1 ?? ??
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD} # ??? ?? ??

  # OAuth2 (Kakao)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI} # http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # AWS S3 (Spring Cloud AWS)
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}
        base_url: ${S3_BUCKET_BASE_URL}

# Actuator (Health Check)
management:
  endpoints:
    web:
      exposure:
        include: health

# Custom JWT Config
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000 # ms 3600000
  refresh-token-validity: 1209600000 # ms

# Logging
logging:
  level:
    root: INFO
    org.sopt: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    groups-order: DESC   # 그룹 정렬 순서
    operations-sorter: method # 메소드 순서대로 정렬
    disable-swagger-default-url: true # 기본 petstore URL 끄기
    display-request-duration: true # 요청 소요 시간 표시


firebase:
  credentials-path: classpath:firebase-service-account.json

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

gemini:
  api-key: ${GEMINI_KEY}

discord:
  webhook-url: ${DISCORD_WEBHOOK}

security:
  encryption-key: ${ENCRYPTION_KEY}
